### ISSUE TITLE
build command fails

### ISSUE THREAD

**Issue by okornienko** [kevin-allen/relectro#9]
R CMD build relectro gives:

* checking for file ‘relectro/DESCRIPTION’ ... OK
cp: cannot stat ‘relectro/tools/missing’: No such file or directory
cp: cannot stat ‘relectro/tools/compile’: No such file or directory
cp: cannot stat ‘relectro/tools/install-sh’: No such file or directory
 ERROR
copying to build directory failed

**Comment by kevin-allen** [comment]
Mostly due to me adding some autotools to control how the c code is compiled. We will sort this on Monday.

**Comment by kevin-allen** [comment]
Here is what I get on my laptop with a freshly cloned directory:

 R CMD build relectro
* checking for file ‘relectro/DESCRIPTION’ ... OK
* preparing ‘relectro’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* running ‘cleanup’
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘relectro_0.0.0.9002.tar.gz’

**Comment by kevin-allen** [comment]
relectro/tools/missing relectro/tools/compile relectro/tools/install-sh were symbolic link instead of the needed file.
This is now working
